# Generated by Django 3.1.5 on 2021-01-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stakeholders',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
