# Generated by Django 3.1.5 on 2021-01-15 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_project_stakeholders'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='endData',
            field=models.DateField(verbose_name='Data de término'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome do projeto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='risk',
            field=models.IntegerField(choices=[(0, 'baixo'), (1, 'medio'), (2, 'alto')], verbose_name='Risco'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stakeholders',
            field=models.CharField(max_length=500, null=True, verbose_name='Participantes'),
        ),
        migrations.AlterField(
            model_name='project',
            name='startData',
            field=models.DateField(verbose_name='Data de início'),
        ),
    ]
